# Generated by Django 5.1.3 on 2024-11-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='Brak tytulu', max_length=255),
            preserve_default=False,
        ),
    ]
