# Generated by Django 5.1.3 on 2024-11-28 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Categories',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='tags',
            new_name='category',
        ),
    ]
