# Generated by Django 5.1.3 on 2024-12-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventregistration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='location',
            new_name='address',
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
