# Generated by Django 5.1.3 on 2025-01-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='available_spots',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
