# Generated by Django 5.1.3 on 2025-01-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_event_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='is_temporary',
            field=models.BooleanField(default=False),
        ),
    ]
